import { colors } from '../../colors.ts';

export const textTokens = {
  'text-primary': colors.grayDark['50'],
  'text-primary_on-brand': colors.grayDark['50'],
  'text-secondary': colors.grayDark['300'],
  'text-secondary_hover': colors.grayDark['200'],
  'text-secondary_on-brand': colors.grayDark['300'],
  'text-tertiary': colors.grayDark['400'],
  'text-tertiary_hover': colors.grayDark['300'],
  'text-tertiary_on-brand': colors.grayDark['400'],
  'text-quaternary': colors.grayDark['400'],
  'text-quaternary_on-brand': colors.grayDark['400'],
  'text-white': colors.baseColors.white,
  'text-disabled': colors.grayDark['500'],
  'text-placeholder': colors.grayDark['400'],
  'text-placeholder_subtle': colors.grayDark['700'],
  'text-brand-primary': colors.grayDark['50'],
  'text-brand-secondary': colors.grayDark['300'],
  'text-brand-tertiary': colors.grayDark['400'],
  'text-brand-tertiary_alt': colors.grayDark['500'],
  'text-error-primary': colors.error['400'],
  'text-warning-primary': colors.warning['400'],
  'text-success-primary': colors.success['400'],
};
